### ISSUE TITLE
低版本手机圆角效果失效

### ISSUE THREAD

**Issue by LLQQHH** [KuangGang/RoundCorners#10]
android4.4手机上圆角失效，看了一下你的代码好像6.0一下做不同的Xfermode出来，但是其他类似效果的开源库没有失效如NiceImageView
![QQ截图20210121103927](https://user-images.githubusercontent.com/19651932/105272861-29a87680-5bd5-11eb-889f-4f844062287d.png)

**Comment by KuangGang** [comment]
您好目前我们把最低版本挪移到了5.0

**Comment by LLQQHH** [comment]
这是干脆不兼容5.0以下的节奏了吗

**Comment by KuangGang** [comment]
我们的APP都到最低23了，不升级兼容问题太多，而且4.x及以下用户占比非常少了
