### ISSUE TITLE
Android10 圆角边框有

### ISSUE THREAD

**Issue by AndMy** [KuangGang/RoundCorners#11]
如下图片
![image](https://user-images.githubusercontent.com/7222340/113811380-b5767b80-979e-11eb-8353-735d496d9a5a.png)

**Comment by hjqiaho** [comment]
Android8.1 也是
demo第一个圆形图片 左边有一条线

**Comment by 3swordzoro** [comment]
我也遇到这个问题了，Android10.
有stroke的时候，canvas发生了scale就会出现。但是还不知道原因。

**Comment by 3swordzoro** [comment]
应该是drawpath的时候，图片左右两边的一像素露出来了

**Comment by 3swordzoro** [comment]
还有，我原本是centerCrop的时候左右两边会有一条线。改成fitXY就好了。

**Comment by KuangGang** [comment]
您好，该问题在最新的1.3.0中已解决
