### ISSUE TITLE
RoundViewPager有问题

### ISSUE THREAD

**Issue by Thomas-Yeh** [KuangGang/RoundCorners#2]
RoundViewPager只有第一页能显示内容，后面的都是空白的，并且圆角没有裁剪

**Comment by KuangGang** [comment]
您好，确实是有问题，ViewPager的绘制加载与其他控件不同，新版本我已删除RoundViewPager。
给您提供两种替换方案：
1.使用RoundFrameLayout包裹ViewPager.
2.ViewPager内部控件使用RoundXXXX.
