### ISSUE TITLE
Android 5.1 使用闪退问题

### ISSUE THREAD

**Issue by YeYuDao** [KuangGang/RoundCorners#3]
日志如下：
#16002 SIGSEGV(SEGV_MAPERR)
com.kproduce.roundcorners.RoundHelper.drawPath(SourceFile:131)

**Comment by YeYuDao** [comment]
解决了，把逆时针方向绘制改成顺时针绘制。

**Comment by KuangGang** [comment]
您使用的什么版本，在1.0.6中已经修复
