### ISSUE TITLE
当宽高不一致的时候出现重大bug

### ISSUE THREAD

**Issue by LLQQHH** [KuangGang/RoundCorners#9]
真机小米4  Android6.0版本，还有模拟器都会出现这个问题
<com.kproduce.roundcorners.RoundImageView
                    android:layout_width="300dp"
                    android:layout_height="200dp"
                    android:scaleType="centerCrop"
                    android:src="@mipmap/ic_test"
                    app:rRadius="40dp"
                    app:rStrokeColor="#26FF0000"
                    app:rStrokeWidth="20dp"/>
这是你demo里面随便改下图片宽高，使宽高不一致就会出现这个bug
![QQ截图20210115145256](https://user-images.githubusercontent.com/19651932/104691537-6392fc00-5741-11eb-87b5-96746a656c10.png)

**Comment by KuangGang** [comment]
收到，感谢反馈，您可以先用RoundLinearLayout包一下ImageView使用，我会尽快修复

<com.kproduce.roundcorners.RoundLinearLayout
        android:layout_width="300dp"
        android:layout_height="200dp"
        android:layout_marginTop="40dp"
        app:rRadius="40dp"
        app:rStrokeColor="#26FF0000"
        app:rStrokeWidth="20dp">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop"
                android:src="@mipmap/ic_test" />

</com.kproduce.roundcorners.RoundLinearLayout>

**Comment by KuangGang** [comment]
新版本1.3.0已解决该问题
